### ISSUE TITLE
change export html style

### ISSUE THREAD

**Issue by jeffie** [rhiokim/haroopad#342]
how to change the exported html style?such as `body font`.i had edit the preview `s default.css,but it`s not work

**Comment by rhiokim** [comment]
Please follow step!
- Execute Haroopad
- Open Preference Window.
- Click Viewer tab.
- Click Edit button in _Your Style_ section
- Modify default.css
- Insert your css ( Any Style Sheet )

**example**

``` css
p {
  color: red;
}
```
- Save default.css
- Click Reload button
- Done.

**Comment by duola** [comment]
![](http://i.imgur.com/sGmp7kl.png)
![](http://i.imgur.com/DrQYf7c.png)
I can't change body font too.
Even though I wrote like this:

```
body {
    font-family: "Microsoft YaHei",Simsun, Helvetica, arial, sans-serif;
    font-size: 14px;
}
```

or

```
div {
    font-family: "Microsoft YaHei",Simsun, Helvetica, arial, sans-serif;
    font-size: 14px;
}
```

**Comment by jeffie** [comment]
tks! i done what you say,it`s really work,but i find that when i click reload ,will build a .userStyle.css file ,and in fact it affect the preview `s style;when i open the file,oh,no!the css became like this:  

``` css
#root body {
}
```

so,the `#root` for what?  when i del `#root`,all work normal!  
@duola (chinese?) you can change your css like this:   

``` css
body {
    font-family: "Microsoft YaHei",Simsun, Helvetica, arial, sans-serif !important;
    font-size: 14px !important;
}
```

**Comment by duola** [comment]
@jeffie
![](http://i.imgur.com/RuubKPX.png)
删除 `#root` 也还是不行。
When I delete the `#root` that can't change body font too

![](http://i.imgur.com/yntknL6.png)
按照你说的如果换成 `body`\+ `!impotant` 也不行，但改成`p`就行。
I replaced `p` with `body`, but it does'nt work as before. Only  work by `p`.

**Comment by jeffie** [comment]
@duola sorry,it do not mean del `#root`,it will be reloaded when you del `root`,so the .userStyle.css will turns back into before the change.  
i do not find a good way to solve this problem(@rhiokim why add a `#root`?),but you can do follow this:  

``` css
html,body{
    font-family: "Microsoft YaHei",Simsun, Helvetica, arial, sans-serif !important;
    font-size: 14px !important;
}
```

or 

``` css
body,.markdown{
    font-family: "Microsoft YaHei",Simsun, Helvetica, arial, sans-serif !important;
    font-size: 14px !important;
}
```

so when you reload it will become like this:  

``` css
#root html,body{
    font-family: "Microsoft YaHei",Simsun, Helvetica, arial, sans-serif !important;
    font-size: 14px !important;
}
```

then the `html` will be invalid,but the `body` can work!  
ps:天王盖地虎
