### ISSUE TITLE
Export Issue

### ISSUE THREAD

**Issue by qiuliang** [rhiokim/haroopad#365]
When i customize a preview theme, and then export to a html file, the application was crashed

![image](https://cloud.githubusercontent.com/assets/1324024/3440787/c425d252-00fb-11e4-82d9-d20707756766.png)

and the preview window is not apply my customization style. for example :

``` css
body{font-family: "宋体"}
```

Would you provide some advice? thank you.

Haroopad Version : `0.12`

**Comment by rhiokim** [comment]
**custom css**

``` css
body * {
  font-family: "宋体"
}
```

If it do not work,  `!important` should be insert to your css style.

``` css
body * {
  font-family: "宋体" !important
}
```

**Comment by qiuliang** [comment]
thanks for your reply!

 I modify the css file according to your opinion, but it doesn't work

**Comment by rhiokim** [comment]
@qiuliang 
Do you want to change font-family within code block?

``` css
code {
  font-family: "宋体"
}
```

or

``` css
pre>code {
  font-family: "宋体"
}
```
