### ISSUE TITLE
support custom fonts

### ISSUE THREAD

**Issue by rhiokim** [rhiokim/haroopad#87]
- system fonts
- google's web fonts

preferences window -> editor -> select font

**Comment by wedens** [comment]
very important feature! especially on linux

**Comment by phrozen** [comment]
Yeah, I truly dislike the default font, I guess here or with custom css themes, changing the font would be a breeze.

**Comment by blockloop** [comment]
+1 for selecting a custom font

**Comment by rhiokim** [comment]
Starting with v0.7
1. Create **[your-theme-name]**.css
2. Write your style (font, margin, color and so on)  
   **Importatnt `.custom { }` selector**  

``` css
@import url(http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic);

.custom {
    font-family: 'PT Sans', sans-serif;
}
```
1. Save to specify your theme folder
2. File > Preferences > Custom > Select theme directory  
   ![](http://pad.haroopress.com/docs/preferences-custom-theme/images/003.png)
3. Select **[your-theme-name]** in Select Box
   ![](http://pad.haroopress.com/docs/preferences-custom-theme/images/005.png)
- [Full Example](http://pad.haroopress.com/docs/preferences-custom-theme/res/example.css)
